globals:
  feelings:
    - Angry
    - Worried
    - Anxious
    - Nervous
    - Sad
    - Scared
    - Mad
    - Okay
    - Content
  thinking:
    - It's just too hard
    - I'm a failure
    - I don't have what it takes to succeed
    - No one can help me
  concerns:
    - I'll skip school
    - I'll do a bad job
  successful_thinking:
    - I have the talents and abilities to succeed
    - I will work hard and improve
    - I see myself reaching my goals
  successful_behaviors:
    - Ask for help from an adult
    - Make a plan # (to study, to prepare, to fix something)
    - Say I'm sorry
    - Stop behaviors that keep you from succeeding
    - Practice positive self-talk
categories:
  school:
    title: School
    challenges:
      - I failed a test
      - I'm failing a class
      - I'm late to my classes
      - I don't get along with people at school
    thinking:
      - I'm not good in this subject
      - I'm not good at school work
      - There is too much pressure
    feelings: []
    concerns:
      - I'll fail a class
      - I'll cheat on a test
      - I won't graduate
    successful_thinking: []
  trouble:
    title: Trouble
    challenges:
      - I got in trouble
      - I got suspended
      - I talked back to my parents
      - I got sent to the office
    thinking:
      - I don't get along with someone important to me
      - I don't want to get along with someone
      - I can't stop saying things I don't mean
    feelings: []
    concerns:
      - I'll get into a fight
      - I'll yell at someone important to me
      - I'll lose my friend
      - I'll cheat on a test
    successful_thinking: []
  attitude:
    title: Attitude
    challenges:
      - I have a bad attitude
      - I cannot control my emotions
      - I'm letting things bring me down
    thinking:
      - I just don't want to do anything
    feelings: []
    concerns:
      - I'll yell at someone important to me
      - I'll lose my friend
      - I'll hurt someone I care about
    successful_thinking: []
