globals:
  feelings:
    - text: Angry
      icon: rage
    - text: Worried
      icon: worried
    - text: Anxious
      icon: sweat
    - text: Nervous
      icon: disappointed_relieved
    - text: Sad
      icon: disappointed
    - text: Scared
      icon: fearful
    - text: Mad
      icon: angry
    - text: Okay
      icon: slight_smile
    - text: Content
      icon: upside_down
  thoughts:
    - text: It's just too hard
      icon: weary
    - text: I'm a failure
      icon: disappointed
    - text: I don't have what it takes to succeed
      icon: confounded
    - text: No one can help me
      icon: sweat
  concerns:
    - text: I'll skip school
      icon: writing_hand
    - text: I'll do a bad job
      icon: frowning2
  positive_thoughts:
    - text: I have the talents and abilities to succeed
      icon: nerd
    - text: I will work hard and improve
      icon: smile
    - text: I see myself reaching my goals
      icon: sunglasses
  positive_behaviors:
    - text: Ask for help from an adult
      icon: handshake
    - text: Make a plan # (to study, to prepare, to fix something)
      icon: thumbsup
    - text: Say I'm sorry
      icon: hugging
    - text: Stop behaviors that keep you from succeeding
      icon: raised_hand
    - text: Practice positive self-talk
      icon: grin
categories:
  school:
    title: School
    challenges:
      - text: I failed a test
        icon: writing_hand
      - text: I'm failing a class
        icon: confused
      - text: I'm late to my classes
        icon: disappointed_relieved
      - text: I don't get along with people at school
        icon: persevere
    thoughts:
      - text: I'm not good in this subject
        icon: pensive
      - text: I'm not good at school work
        icon: slight_frown
      - text: There is too much pressure
        icon: weary
    feelings: []
    concerns:
      - text: I'll fail a class
        icon: thumbsdown
      - text: I'll cheat on a test
        icon: fingers_crossed
      - text: I won't graduate
        icon: mortar_board
    positive_thoughts: []
    positive_behaviors: []
  trouble:
    title: Trouble
    challenges:
      - text: I got in trouble
        icon: sweat
      - text: I got suspended
        icon: punch
      - text: I talked back to my parents
        icon: triumph
      - text: I got sent to the office
        icon: point_right
    thoughts:
      - text: I don't get along with someone important to me
        icon: disappointed
      - text: I don't want to get along with someone
        icon: unamused
      - text: I can't stop saying things I don't mean
        icon: zipper_mouth
    feelings: []
    concerns:
      - text: I'll get into a fight
        icon: punch
      - text: I'll yell at someone important to me
        icon: angry
      - text: I'll lose my friend
        icon: weary
      - text: I'll cheat on a test
        icon: slight_frown
    positive_thoughts: []
    positive_behaviors: []
  attitude:
    title: Attitude
    challenges:
      - text: I have a bad attitude
        icon: angry
      - text: I cannot control my emotions
        icon: zipper_mouth
      - text: I'm letting things bring me down
        icon: pensive
    thoughts:
      - text: I just don't want to do anything
        icon: expressionless
    feelings: []
    concerns:
      - text: I'll yell at someone important to me
        icon: triumph
      - text: I'll lose my friend
        icon: weary
      - text: I'll hurt someone I care about
        icon: angry
    positive_thoughts: []
    positive_behaviors: []
